# Generated by Django 4.2.5 on 2025-10-02 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=5)),
                ('color', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('running', 'Running'), ('sport', 'Sport'), ('casual', 'Casual')], max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('discount_percent', models.PositiveIntegerField(blank=True, help_text='Discount percent 0-100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
